In [ ]:
import numpy as np
import pandas as pd
 
train = pd.read_csv("C:/Users/lenovo/Desktop/d_train_20180102.csv",encoding="GB2312")
print(train.head())

# 设置pandas的显示选项，以控制DataFrame的显示格式 
# 最大行数设置为10，以避免显示过多的数据而使结果混乱  
pd.set_option('display.max_rows', 10)
# 最大列数设置为10，以避免显示过多的列而使结果混乱  
pd.set_option('display.max_columns', 10)
# 设置每行的显示宽度为1000字符，这有助于更好地查看数据
pd.set_option('display.width', 1000)

data = pd.read_csv("C:/Users/lenovo/Desktop/d_train_20180102.csv",encoding="GB2312")
# 打印"train" DataFrame的前五行，以查看数据的初步情况  
data.head(5)
 
import matplotlib.pyplot as plt
import seaborn as sns
from pylab import mpl
## 统计"data" DataFrame中的重复行数量，并打印结果
print("共有重复行：", data.duplicated().sum())  #统计重复值
# 检查"data" DataFrame中哪些列包含缺失值（NaN），并打印结果
print(data.isnull().any())  # 判断哪些列包含缺失值
# 统计"data" DataFrame中每列缺失值的数量，并打印结果
print(data.isnull().sum())  # 判断每列缺失值的数量
# 将缺失值统计结果存储在名为"missdata"的变量中  
missdata = data.isnull().sum()
# 使用describe()方法对"missdata"进行描述性统计，并打印结果（包括计数、平均值、标准差等）  
print(round(missdata.describe()))  #统计缺失值



In [ ]:
# 显示各特征缺失比例
null_percentage = (data.isnull().sum() / len(data)).apply(lambda x: '{:.2%}'.format(x))  # 计算每列缺失比例
print (null_percentage)
# 查看血糖值是否有非均衡性的共性
sns.set()# 使用seaborn的默认主题设置  
ax = sns.histplot(data["血糖"], kde=False, bins=300) # 使用seaborn的histplot函数绘制血糖值的直方图，kde参数为False表示不绘制核密度估计，bins参数设定了直方图的柱子数量 
ax.set_title("血糖数据直方图")
ax.set_xlabel("血糖值")
ax.set_ylabel("比例")

total_samples = len(data["血糖"])# 计算血糖值的样本总数  
relative_frequencies = (ax.get_yticks() / total_samples) * 100# 计算直方图中每个柱子的相对频率（即该柱子的高度/样本总数）并乘以100得到百分比形式  
# 将y轴标签设置为百分比格式  
# 将y轴标签设置为百分比格式
ax.set_yticks(ax.get_yticks())
ax.set_yticklabels([f"{freq:.2f}%" for freq in relative_frequencies])

plt.xlim(0, 18)# 设置x轴的显示范围为0到18  
plt.rcParams['font.sans-serif'] = ['SimHei'] # 设置matplotlib的字体为'SimHei'，以便能够正常显示中文标签  
plt.show()

In [ ]:
# 读取训练数据集，使用GB2312编码格式解码  
train = pd.read_csv("C:/Users/lenovo/Desktop/d_train_20180102.csv",encoding="GB2312")
# 测试集
test = pd.read_csv("C:/Users/lenovo/Desktop/d_train_20180102.csv",encoding="GB2312")
# 删除训练集缺失率过大特征、无效的时间特征
del_feat=['乙肝表面抗原', '乙肝表面抗体', '乙肝e抗原', '乙肝e抗体', '乙肝核心抗体', '体检日期']
# 创建一个空列表，用于存储除删除特征外的其他特征列名  
feat=[]
# 遍历训练数据集的所有特征列
for i in train.columns:
    # 如果特征列不在删除特征列表中，则将其添加到feat列表中 
    if i not in del_feat:
        feat.append(i)

# 根据feat列表重新选择训练数据集的特征列  
train=train[feat]

#中值补充缺实值
medians = train.median()
train = train.fillna(medians)


# 将"Outcome"列从训练数据集中分离出来作为目标变量y，其他列作为特征x  
y_train = train["Outcome"]
x_train = train.drop(['id','Outcome'], axis=1)
x_test = test.drop(['id','Outcome'], axis=1)

# 用平均值代替缺失值
x_train = x_train.fillna(x_train.mean())
x_test = x_test.fillna(x_test.mean())
data = x_train
null_percentagee = (data.isnull().sum() / len(data)).apply(lambda x: '{:.2%}'.format(x))  # 计算每列缺失比例
print (null_percentagee)

# 获取特征列的名称列表  
feat_names = x_train.columns


# 数据标准化
# from sklearn.preprocessing import StandardScaler

# # 初始化特征的标准化器
# ss_x = StandardScaler()
# # 分别对训练和测试数据的特征进行标准化处理
# x_train = ss_x.fit_transform(x_train)
#存为csv格式
# 将处理后的训练数据集转换为CSV格式并保存到指定路径  
x_train = pd.DataFrame(columns = feat_names, data = x_train)
 
train = pd.concat([x_train, y_train], axis = 1)
 
train.to_csv('C:/Users/lenovo/Desktop/pima2-diabetes.csv',index = False,header=True)# 将处理后的数据保存为CSV文件，不包含索引，包含表头
 
print(train.head())












In [1]:
import numpy as np
import pandas as pd
#from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.preprocessing import LabelEncoder
# 数据标准化
from sklearn.preprocessing import StandardScaler

# 初始化特征的标准化器
ss_x = StandardScaler()

#导入csv数据
df = pd.read_csv("C:/Users/lenovo/Desktop/pima2-diabetes.csv")
#   x为可能导致糖尿病的因素
x = df.drop('Outcome', axis=1)
#   y为诊断结果，1为确诊，2为未确诊
y = df['Outcome']

#   训练数据(随机森林)
def random_forest():
    #   将数据标准化
    X = df.drop('Outcome', axis=1)
    #X = ss_x.fit_transform(X)
    # 一共768个数据738个作为训练集，30个作为测试集
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=600 / 5643, random_state=0)
    # 若数值过大可以标准化，这里数值不算大，标准化后准确值较低，所以注释掉了不进行标准化
    classifier = RandomForestClassifier(criterion='entropy', n_estimators=1000, max_depth=None, min_samples_split=10,
                                            min_weight_fraction_leaf=0.02)
    classifier.fit(X_train, y_train)
    y_pred = classifier.predict(X_test)
    print('随机森林准确率')
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    print(accuracy_score(y_test, y_pred))
    print('模型得分:{:.2f}'.format(classifier.score(X_test, y_test)))
    y_ = np.array(y_test)
    print('随机森林预测结果：', classifier.predict(X_test))
    print('真实结果:         ', y_)
    print('-------------------------------------------')


In [2]:
#def decision_tree():
X = df.drop('Outcome', axis=1)
#X = ss_x.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=100 / 5643)
# 参数是经过测试得到的最高准确率的参数
classifier = DecisionTreeClassifier(criterion='entropy', max_depth=3, min_weight_fraction_leaf=0.01)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
print(X_test)
print(y_pred)
print('决策树准确率')
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print('模型得分:{:.2f}'.format(classifier.score(X_test, y_test)))
y_ = np.array(y_test)
print('决策树预测结果：', classifier.predict(X_test))
print('真实结果:         ', y_)
print('--------------------------------------------------------------------------------------')


      年龄  *天门冬氨酸氨基转换酶  *丙氨酸氨基转换酶  *碱性磷酸酶  *r-谷氨酰基转换酶   *总蛋白    白蛋白   *球蛋白  \
3750  42        23.89      21.48   84.47       26.19  76.63  45.82  30.78   
806   21        23.89      21.48   84.47       26.19  76.63  45.82  30.78   
3983  35        23.89      21.48   84.47       26.19  76.63  45.82  30.78   
3948  44        23.89      21.48   84.47       26.19  76.63  45.82  30.78   
4198  58        21.51      17.63   87.48       18.93  74.50  46.86  27.64   
...   ..          ...        ...     ...         ...    ...    ...    ...   
5261  31        29.18      41.44   74.41       63.84  76.42  43.91  32.51   
4340  30        22.28      38.64  110.78       32.79  75.47  47.47  28.00   
2193  38        18.82      12.79   77.09       21.66  82.68  46.54  36.14   
1399  30        23.89      21.48   84.47       26.19  76.63  45.82  30.78   
1845  77        24.84      19.89   78.06       25.26  78.88  44.66  34.22   

      白球比例  甘油三酯  ...  血小板计数  血小板平均体积  血小板体积分布宽度  血小板比积  中性粒细胞%  淋巴细胞%  单核细

In [ ]:
#   训练数据（逻辑回归）
def logistic_regression():
    X = df.drop('Outcome', axis=1)
    X = ss_x.fit_transform(X)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=30 / 768, random_state=0)
    lr = LogisticRegression(random_state=0, max_iter=1000)
    lr.fit(X_train, y_train)
    y_pred = lr.predict(X_test)
    print('逻辑回归准确率')
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    print(accuracy_score(y_test, y_pred))
    print('模型得分:{:.2f}'.format(lr.score(X_test, y_test)))
    y_ = np.array(y_test)
    print('逻辑回归预测结果：', lr.predict(X_test))
    print('真实结果:         ', y_)
    print('--------------------------------------------------------------------------------------')


In [ ]:

#   训练数据（KNN）寻找最佳的k值
#def k_nn():
X = df.drop('Outcome', axis=1)
X = ss_x.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=30 / 768, random_state=0)
error = []
# 由于一开始并不清楚K取多少准确率最高，所以写了一个K为1-14的for循环，通过检查误差值来判断最合适的K值
for k in range(1, 15):
    classifier = KNeighborsClassifier(n_neighbors=k)
    classifier.fit(X_train, y_train)
    y_prediction = classifier.predict(X_test)
    error.append(np.mean(y_prediction != y_test))
    print('当k=', k, '时的准确率')
    print(confusion_matrix(y_test, y_prediction))
    print(classification_report(y_test, y_prediction))
    print('模型得分:{:.2f}'.format(classifier.score(X_test, y_test)))
    print('--------------------------------------------------------------------------------------')


In [ ]:
def n_n():
    X = df.drop('Outcome', axis=1)
    X = ss_x.fit_transform(X)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=30 / 768, random_state=0)
    mlp = MLPClassifier(random_state=0, max_iter=5000)
    mlp.fit(X_train, y_train)
    y_pred = mlp.predict(X_test)
    print('Neural Network准确率')
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    print(accuracy_score(y_test, y_pred))
    print('模型得分:{:.2f}'.format(mlp.score(X_test, y_test)))
    y_ = np.array(y_test)
    print('Neural Network预测结果：', mlp.predict(X_test))
    print('真实结果:         ', y_)
    print('--------------------------------------------------------------------------------------')



In [ ]:
from xgboost import XGBClassifier

def xgb():
    X = df.drop('Outcome', axis=1)
    X = ss_x.fit_transform(X)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=30 / 768, random_state=0)
    xgb = XGBClassifier(gamma=0, use_label_encoder=False, learning_rate=0.01, max_depth=10, n_estimators=10000, random_state=34, reg_lambda=6, reg_alpha=3, verbosity=0)
    xgb.fit(X_train, y_train)
    y_prediction = xgb.predict(X_test)
    print('XGBoost准确率')
    print(confusion_matrix(y_test, y_prediction))
    print(classification_report(y_test, y_prediction))
    print(accuracy_score(y_test, y_prediction))
    print('模型得分:{:.2f}'.format(xgb.score(X_test, y_test)))
    y_ = np.array(y_test)
    print('XGBoost预测结果：', xgb.predict(X_test))
    print('真实结果:         ', y_)
    print('--------------------------------------------------------------------------------------')
    


In [5]:
import numpy as np
import pandas as pd
#from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.preprocessing import LabelEncoder
from xgboost import XGBClassifier
# 数据标准化
from sklearn.preprocessing import StandardScaler
import joblib


# 初始化特征的标准化器
ss_x = StandardScaler()

#导入csv数据
df = pd.read_csv("C:/Users/lenovo/Desktop/pima2-diabetes.csv")
#   x为可能导致糖尿病的因素
x = df.drop('Outcome', axis=1)
#   y为诊断结果，1为确诊，2为未确诊
y = df['Outcome']

#   训练数据(随机森林)
def random_forest():
    #   将数据标准化
    X = df.drop('Outcome', axis=1)
    #X = ss_x.fit_transform(X)
    # 一共768个数据738个作为训练集，30个作为测试集
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=100 / 5643, random_state=0)
    # 若数值过大可以标准化，这里数值不算大，标准化后准确值较低，所以注释掉了不进行标准化
    classifier = RandomForestClassifier(criterion='entropy', n_estimators=1000, max_depth=None, min_samples_split=10,
                                            min_weight_fraction_leaf=0.02)
    classifier.fit(X_train, y_train)
    y_pred = classifier.predict(X_test)
    print('随机森林准确率')
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    print(accuracy_score(y_test, y_pred))
    print('模型得分:{:.2f}'.format(classifier.score(X_test, y_test)))
    y_ = np.array(y_test)
    print('随机森林预测结果：', classifier.predict(X_test))
    print('真实结果:         ', y_)
    print('-------------------------------------------')
    joblib.dump(classifier, 'model1.pkl')


#model1:随机
#model2:决策
#model3:逻辑
#model4:k_nn
#model5:神经网络
#model6:xgboost


#决策树
def decision_tree():
    X = df.drop('Outcome', axis=1)
    #X = ss_x.fit_transform(X)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=100 / 5643)
    # 参数是经过测试得到的最高准确率的参数
    classifier = DecisionTreeClassifier(criterion='entropy', max_depth=3, min_weight_fraction_leaf=0.01)
    classifier.fit(X_train, y_train)
    y_pred = classifier.predict(X_test)
    print('决策树准确率')
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    print(accuracy_score(y_test, y_pred))
    print('模型得分:{:.2f}'.format(classifier.score(X_test, y_test)))
    y_ = np.array(y_test)
    print('决策树预测结果：', classifier.predict(X_test))
    print('真实结果:         ', y_)
    print('--------------------------------------------------------------------------------------')
    joblib.dump(classifier, 'model2.pkl')

#   训练数据（逻辑回归）
def logistic_regression():
    X = df.drop('Outcome', axis=1)
    #X = ss_x.fit_transform(X)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=100 / 5643, random_state=0)
    lr = LogisticRegression(random_state=0, max_iter=1000)
    lr.fit(X_train, y_train)
    y_pred = lr.predict(X_test)
    print('逻辑回归准确率')
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    print(accuracy_score(y_test, y_pred))
    print('模型得分:{:.2f}'.format(lr.score(X_test, y_test)))
    y_ = np.array(y_test)
    print('逻辑回归预测结果：', lr.predict(X_test))
    print('真实结果:         ', y_)
    print('--------------------------------------------------------------------------------------')
    joblib.dump(lr, 'model3.pkl')

#   训练数据（KNN）寻找最佳的k值
def k_nn():
    X = df.drop('Outcome', axis=1)
    #X = ss_x.fit_transform(X)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=100 / 5643, random_state=0)
    error = []
    # 由于一开始并不清楚K取多少准确率最高，所以写了一个K为1-14的for循环，通过检查误差值来判断最合适的K值
    for k in range(1, 15):
        classifier = KNeighborsClassifier(n_neighbors=k)
        classifier.fit(X_train, y_train)
        y_prediction = classifier.predict(X_test)
        error.append(np.mean(y_prediction != y_test))
        print('当k=', k, '时的准确率')
        print(confusion_matrix(y_test, y_prediction))
        print(classification_report(y_test, y_prediction))
        print('模型得分:{:.2f}'.format(classifier.score(X_test, y_test)))
        print('--------------------------------------------------------------------------------------')
        joblib.dump(classifier, 'model4.pkl')

#神经网络模型
def n_n():
    X = df.drop('Outcome', axis=1)
    #X = ss_x.fit_transform(X)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=100 / 5643, random_state=0)
    mlp = MLPClassifier(random_state=0, max_iter=5000)
    mlp.fit(X_train, y_train)
    y_pred = mlp.predict(X_test)
    print('Neural Network准确率')
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    print(accuracy_score(y_test, y_pred))
    print('模型得分:{:.2f}'.format(mlp.score(X_test, y_test)))
    y_ = np.array(y_test)
    print('Neural Network预测结果：', mlp.predict(X_test))
    print('真实结果:         ', y_)
    print('--------------------------------------------------------------------------------------')
    joblib.dump(mlp, 'model5.pkl')

#XGBOOST
def xgb():
    X = df.drop('Outcome', axis=1)
    #X = ss_x.fit_transform(X)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=100 / 5643, random_state=0)
    xgb = XGBClassifier(gamma=0, use_label_encoder=False, learning_rate=0.01, max_depth=10, n_estimators=10000, random_state=34, reg_lambda=6, reg_alpha=3, verbosity=0)
    xgb.fit(X_train, y_train)
    y_prediction = xgb.predict(X_test)
    print('XGBoost准确率')
    print(confusion_matrix(y_test, y_prediction))
    print(classification_report(y_test, y_prediction))
    print(accuracy_score(y_test, y_prediction))
    print('模型得分:{:.2f}'.format(xgb.score(X_test, y_test)))
    y_ = np.array(y_test)
    print('XGBoost预测结果：', xgb.predict(X_test))
    print('真实结果:         ', y_)
    print('--------------------------------------------------------------------------------------')
    joblib.dump(xgb, 'model6.pkl')
    

#   主菜单
def main_menu():
    print('-' * 11, '糖尿病诊断预测', '-' * 11)
    print('|{:20}|{:20}|'.format('1.输入指标', '2.退出系统'))
 
 
#   选择模型菜单
def option_menu():
    print('-' * 11, '训练模型选择', '-' * 11)
    print('|{:20}|{:20}|'.format('1.所有模型', '2.随机森林'))
    print('|{:20}|{:20}|'.format('3.决策树', '4.逻辑回归'))
    print('|{:23}|{:20}|'.format('5.KNN', '6.连接模型'))
    print('|{:23}|'.format('7.XGBoost'))

 
 
#   登出
def logout():
    print('感谢使用')
 
if __name__ == '__main__':
    while True:
        main_menu()
        key = input('请输入你的选择: ')
        if key == '1':
            try:
                ID = float(input('id:'))
                Pregnancy = float(input('*天门冬氨酸氨基转换酶：'))
                Glu = float(input('*丙氨酸氨基转换酶：'))
                BP = float(input('*碱性磷酸酶：'))
                ST = float(input('*r-谷氨酰基转换酶：'))
                Ins = float(input('*总蛋白：'))
                BMI = float(input('白蛋白：'))
                DBF = float(input('*球蛋白：'))
                Age = float(input('白球比例：'))
                Aae = float(input('甘油三酯：'))
                Abe = float(input('总胆固醇：'))
                Ace = float(input('高密度脂蛋白胆固醇：'))
                Ade = float(input('低密度脂蛋白胆固醇：'))
                Aee = float(input('尿素：'))
                Afe = float(input('肌酐：'))
                Ahe = float(input('尿酸：'))
                Aie = float(input('白细胞计数：'))
                Aje = float(input('红细胞计数：'))
                Ake = float(input('血红蛋白：'))
                Ale = float(input('红细胞压积：'))
                Ame = float(input('红细胞平均体积：'))
                Ane = float(input('红细胞平均血红蛋白量：'))
                Aoe = float(input('红细胞平均血红蛋白浓度：'))
                Ape = float(input('红细胞体积分布宽度：'))
                Aqe = float(input('血小板计数：'))
                Are = float(input('血小板平均体积：'))
                Ase = float(input('血小板体积分布宽度：'))
                Ate = float(input('血小板比积：'))
                Aue = float(input('中性粒细胞%：'))
                Ave = float(input('淋巴细胞%：'))
                Awe = float(input('单核细胞%：'))
                Axe = float(input('嗜酸细胞%：'))
                Aye = float(input('嗜碱细胞%：'))
                Aze = float(input('血糖：'))
            except:
                print("不符合输入要求，请重新输入")
                continue
			# 将输入的值放在一个列表中
            indices = [Pregnancy, Glu, BP, ST, Ins, BMI, DBF, Age,Aae,Abe,Ace,
                      Ade,Aee,Afe,Ahe,Aie,Aje,Ake,Ale,Ame,Ane,Aoe,Ape,Aqe,Are,
                      Ase,Ate,Aue,Ave,Awe,Axe,Aye,Aze,ID]
            l = []
            #indices = np.array(indices).reshape(1, -1)
            for index in indices:
                l.append(index)
 
            empty_indices = {"Pregnancies": l[0], "Glucose": l[1], 
                             "BloodPressure": l[2], "SkinThickness": l[3],
                             "Insulin": l[4], "BMI": l[5], 
                             "DiabetesPedigreeFunction": l[6], "Age": l[7],
                             "Aae":l[8],"Abe":l[9],"Ace":l[10],"Ade":l[11],
                             "Aee":l[12],"Afe":l[13],"Ahe":l[14],"Aie":l[15],
                             "Aje":l[16],"Ake":l[17],"Ale":l[18],"Ame":l[19],
                             "Ane":l[20],"Aoe":l[21],"Ape":l[22],"Aqe":l[23],
                             "Are":l[24],"Ase":l[25],"Ate":l[26],"Aue":l[27],
                             "Ave":l[28],"Awe":l[29],"Axe":l[30],"Aye":l[31],
                             "Aze":l[32],"ID":l[33]
                            }
            data = pd.DataFrame(empty_indices, index=[0])
            data = data.set_index('Pregnancies')
            data.to_csv("new.csv")
            df_1 = pd.read_csv("new.csv")
            s = df_1.iloc[0]
            s = np.array(s).reshape(1, -1)
            print(s)
            a = s[0]
            print(a)
            # 选择模型菜单
            option_menu()
            option = input('请选择模型：')
            #   显示所有的训练模型结果
            if option == '1':
                random_forest()
                decision_tree()
                logistic_regression()
                k_nn()
                n_n()
                xgb()
                classifier = joblib.load('model3.pkl') 
                y_pre = classifier.predict(s)
                print("------------------------------------------------------------------")
                print(type(y_pre))
                print(y_pre)
                a = y_pre[0]
                print(a)
                print('******************************************************************')
            elif option == '2':
                random_forest()
            elif option == '3':
                decision_tree()
            elif option == '4':
                logistic_regression()
            elif option == '5':
                k_nn()
            elif option == '6':
                n_n()
            elif option == '7':
                xgb()
            else:
                print('无效输入')
                continue
        elif key == '2':
            logout()
            break
        else:
            print('无效输入')


----------- 糖尿病诊断预测 -----------
|1.输入指标              |2.退出系统              |


请输入你的选择:  1
id: 1
*天门冬氨酸氨基转换酶： 1
*丙氨酸氨基转换酶： 1
*碱性磷酸酶： 1
*r-谷氨酰基转换酶： 1
*总蛋白： 1
白蛋白： 1
*球蛋白： 1
白球比例： 1
甘油三酯： 1
总胆固醇： 1
高密度脂蛋白胆固醇： 1
低密度脂蛋白胆固醇： 1
尿素： 1
肌酐： 1
尿酸： 1
白细胞计数： 1
红细胞计数： 1
血红蛋白： 1
红细胞压积： 1
红细胞平均体积： 1
红细胞平均血红蛋白量： 1
红细胞平均血红蛋白浓度： 1
红细胞体积分布宽度： 1
血小板计数： 1
血小板平均体积： 1
血小板体积分布宽度： 1
血小板比积： 1
中性粒细胞%： 1
淋巴细胞%： 1
单核细胞%： 1
嗜酸细胞%： 1
嗜碱细胞%： 1
血糖： 1


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
----------- 训练模型选择 -----------
|1.所有模型              |2.随机森林              |
|3.决策树               |4.逻辑回归              |
|5.KNN                  |6.连接模型              |
|7.XGBoost              |


请选择模型： 1


随机森林准确率
[[72  0]
 [ 8 20]]
              precision    recall  f1-score   support

           0       0.90      1.00      0.95        72
           1       1.00      0.71      0.83        28

    accuracy                           0.92       100
   macro avg       0.95      0.86      0.89       100
weighted avg       0.93      0.92      0.92       100

0.92
模型得分:0.92
随机森林预测结果： [0 0 1 0 0 1 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 1 0 0 0 1 1 1 0 0 0 0 0 1 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0]
真实结果:          [0 0 1 0 0 1 0 0 0 0 0 1 1 0 1 0 1 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 0 0
 0 0 0 1 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1
 0 0 1 0 0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 1 0]
-------------------------------------------
决策树准确率
[[80  2]
 [ 6 12]]
              precision    recall  f1-score   support

           0       0.93      0.98      0.95        82
           1       

D:\Anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


逻辑回归准确率
[[71  1]
 [ 8 20]]
              precision    recall  f1-score   support

           0       0.90      0.99      0.94        72
           1       0.95      0.71      0.82        28

    accuracy                           0.91       100
   macro avg       0.93      0.85      0.88       100
weighted avg       0.91      0.91      0.91       100

0.91
模型得分:0.91
逻辑回归预测结果： [0 0 1 0 0 1 0 0 0 0 0 0 1 0 1 0 1 0 1 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 1 0 0
 0 0 0 1 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0]
真实结果:          [0 0 1 0 0 1 0 0 0 0 0 1 1 0 1 0 1 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 0 0
 0 0 0 1 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1
 0 0 1 0 0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 1 0]
--------------------------------------------------------------------------------------
当k= 1 时的准确率
[[67  5]
 [20  8]]
              precision    recall  f1-score   support

           0       0.77  

D:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Neural Network准确率
[[70  2]
 [ 7 21]]
              precision    recall  f1-score   support

           0       0.91      0.97      0.94        72
           1       0.91      0.75      0.82        28

    accuracy                           0.91       100
   macro avg       0.91      0.86      0.88       100
weighted avg       0.91      0.91      0.91       100

0.91
模型得分:0.91
Neural Network预测结果： [0 0 1 0 0 1 0 0 0 0 0 0 1 1 1 0 1 0 1 0 0 0 1 0 0 0 1 1 1 0 0 0 0 0 1 0 0
 0 0 0 1 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0]
真实结果:          [0 0 1 0 0 1 0 0 0 0 0 1 1 0 1 0 1 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 0 0
 0 0 0 1 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1
 0 0 1 0 0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 1 0]
--------------------------------------------------------------------------------------
XGBoost准确率
[[71  1]
 [ 6 22]]
              precision    recall  f1-score   support

      

D:\Anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


------------------------------------------------------------------
<class 'numpy.ndarray'>
[1]
1
******************************************************************
----------- 糖尿病诊断预测 -----------
|1.输入指标              |2.退出系统              |


请输入你的选择:  2


感谢使用
